Termin: https://raw.githubusercontent.com/TheOninesixY/flathub/refs/heads/io.github.theoninesixy.Termin/io.github.theoninesixy.Termin.yml
FlatHMCL: https://raw.githubusercontent.com/TheOninesixY/FlatHMCL/refs/heads/main/io.github.theoninesixy.FlatHMCL.yml
RikkaHub: https://raw.githubusercontent.com/TheOninesixY/rikkahub-desktop-flatpak/refs/heads/main/io.github.theoninesixy.RikkaHub.yml
