Termin: https://raw.githubusercontent.com/TheOninesixY/flathub/refs/heads/io.github.theoninesixy.Termin/io.github.theoninesixy.Termin.yml
HMCL: https://raw.githubusercontent.com/TheOninesixY/FlatHMCL/refs/heads/main/io.github.theoninesixy.FlatHMCL.yml
